# Install dependencies only when needed
FROM node:16-alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY . .
RUN yarn install --frozen-lockfile
ARG NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_BASE_URL $NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS
ENV NEXT_PUBLIC_GOOGLE_ANALYTICS $NEXT_PUBLIC_GOOGLE_ANALYTICS
ARG NEXT_PUBLIC_GOOGLE_TAG_MANAGER
ENV NEXT_PUBLIC_GOOGLE_TAG_MANAGER $NEXT_PUBLIC_GOOGLE_TAG_MANAGER
ARG NEXT_PUBLIC_GOOGLE_ADS
ENV NEXT_PUBLIC_GOOGLE_ADS $NEXT_PUBLIC_GOOGLE_ADS
RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]
