apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nwp-website-react-ingress
  namespace: nwp-staging
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: "nwp-website-react.stag.app.nationaalwerknemerplan.nl"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: nwp-website-react
                port:
                  number: 3000
  tls:
    - hosts:
        - "nwp-website-react.stag.app.nationaalwerknemerplan.nl"
      secretName: nwp-website-react-stag-app-nationaalwerknemerplan-nl-tls
