apiVersion: v1
kind: Secret
metadata:
  name: trustlink-fe-env
  namespace: trustlink-staging
type: Opaque
stringData:
  PORT: ''
  SECRET: ''

  DATABASE_HOST: ''
  DATABASE_NAME: ''
  DATABASE_USERNAME: ''
  DATABASE_PASSWORD: ''
  DATABASE_PORT: ''
  DATABASE_CLIENT: ''

  SMTP_SERVICE: ''
  SMTP_USERNAME: ''
  SMTP_PASSWORD: ''