apiVersion: v1
kind: Service
metadata:
  name: nwp-website-react
  namespace: nwp-staging
  labels:
    run: nwp-website-react
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app:  nwp-website-react
