apiVersion: apps/v1
kind: Deployment
metadata:
  name: trustlink-fe
  namespace: trustlink-production
spec:
  selector:
    matchLabels:
      app: trustlink-fe
  replicas: 1
  template:
    metadata:
      labels:
        app: trustlink-fe
    spec:
      containers:
        - name: trustlink-fe
          image: registry-harbor.app.bangun-kreatif.com/trustlink/trustlink-fe:<VERSION>
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred

