apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trustlink-fe
  namespace: trustlink-production
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod-http
    traefik.ingress.kubernetes.io/router.middlewares: trustlink-production-redirect-https@kubernetescrd
spec:
  rules:
    - host: "www.withtrustlink.com"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: trustlink-fe
                port:
                  number: 3000
  tls:
    - hosts:
        - "www.withtrustlink.com"
      secretName: www-withtrustlink-com-tls